kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
      - push
      - pull_request

steps:
  - name: test
    privileged: true
    image: alpine:latest
    commands:
      - sed -i '1i\include "./config-example.conf";' bird.conf
      - apk add bird iproute2
      - ip link add tunnel-dum0 type dummy
      - bird -p -c ./bird.conf

---
kind: pipeline
type: docker
name: updateFilter

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main

steps:
  - name: update filter
    image: debian:latest
    commands:
      - apt-get update -y && apt-get install bgpq4 git -y
      - echo "define $(bgpq4 -tbl DOWNSTREAM_ASN AS-NET186 -S RIPE,ARIN,APNIC,AFRINIC,LACNIC -L 3)" > util/irr-filter.conf
      - echo "define $(bgpq4 -6bl DOWNSTREAM_PREFIXES AS-NET186 -S RIPE,ARIN,APNIC,AFRINIC,LACNIC,RPKI -A -R48)" >> util/irr-filter.conf
      - echo "net.186526.xyz" >> CNAME
      - git rm -f ansible
  - name: push to repo
    image: appleboy/drone-git-push:0.2.3-linux-arm64
    settings:
      branch: production
      remote: git@direct-git.186526.xyz:186526/net186-config.git
      force: true
      commit_message: "[CI] Update: update filter"
      commit: true
      ssh_key:
        from_secret: ssh_private_key
